package sia;
import sia.AgregarInvestigadorDialog;
import sia.AgregarPublicacionDialog;
import sia.EliminarInvestigadorDialog;
import sia.EliminarPublicacionDialog;

public class MásOpcionesDialog extends javax.swing.JDialog {

    private Sistema sistema;
    private String idProyecto;
    
    public MásOpcionesDialog(java.awt.Frame parent, boolean modal, Sistema sistema, String idProyecto) {
       super(parent, modal);
       initComponents();
       this.sistema = sistema;
       this.idProyecto = idProyecto;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarInvestigador = new javax.swing.JButton();
        btnAgregarPublicacion = new javax.swing.JButton();
        btnEliminarPublicacion = new javax.swing.JButton();
        btnEliminarInvestigador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAgregarInvestigador.setText("Agregar Investigador");
        btnAgregarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInvestigadorActionPerformed(evt);
            }
        });

        btnAgregarPublicacion.setText("Agregar Publicación");
        btnAgregarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPublicacionActionPerformed(evt);
            }
        });

        btnEliminarPublicacion.setText("Eliminar Publicación");
        btnEliminarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPublicacionActionPerformed(evt);
            }
        });

        btnEliminarInvestigador.setText("Eliminar Investigador");
        btnEliminarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInvestigadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminarInvestigador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarInvestigador)
                    .addComponent(btnAgregarPublicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarPublicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(btnAgregarInvestigador)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPublicacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarInvestigador)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPublicacion)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    

   
   
    private void btnEliminarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPublicacionActionPerformed
        EliminarPublicacionDialog dialog = new EliminarPublicacionDialog(
        (java.awt.Frame) this.getParent(), true, sistema, idProyecto
        );
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEliminarPublicacionActionPerformed

    private void btnAgregarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInvestigadorActionPerformed
        AgregarInvestigadorDialog dialog = new AgregarInvestigadorDialog(
            (java.awt.Frame) this.getParent(), true, sistema, idProyecto
        );
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarInvestigadorActionPerformed

    private void btnAgregarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPublicacionActionPerformed
        AgregarPublicacionDialog dialog = new AgregarPublicacionDialog(
        (java.awt.Frame) this.getParent(), true, sistema, idProyecto
        );
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarPublicacionActionPerformed

    private void btnEliminarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInvestigadorActionPerformed
        // Obtén el nombre del usuario. Si tienes una variable para eso, úsala.  
        EliminarInvestigadorDialog dialog = new EliminarInvestigadorDialog(
        (java.awt.Frame) this.getParent(), true, sistema, idProyecto
    );
    dialog.setVisible(true);
    }//GEN-LAST:event_btnEliminarInvestigadorActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInvestigador;
    private javax.swing.JButton btnAgregarPublicacion;
    private javax.swing.JButton btnEliminarInvestigador;
    private javax.swing.JButton btnEliminarPublicacion;
    // End of variables declaration//GEN-END:variables
}
