/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sia;

/**
 *
 * @author felix
 */
public class MásOpcionesDialog extends javax.swing.JDialog {

    private Sistema sistema;
    private String idProyecto;
    
    public MásOpcionesDialog(java.awt.Frame parent, boolean modal, Sistema sistema, String idProyecto) {
       super(parent, modal);
       initComponents();
       this.sistema = sistema;
       this.idProyecto = idProyecto;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarInvestigador = new javax.swing.JButton();
        btnAgregarPublicacion = new javax.swing.JButton();
        btnEliminarPublicacion = new javax.swing.JButton();
        btnEliminarInvestigador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAgregarInvestigador.setText("Agregar Investigador");

        btnAgregarPublicacion.setText("Agregar Publicación");

        btnEliminarPublicacion.setText("Eliminar Publicación");
        btnEliminarPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPublicacionActionPerformed(evt);
            }
        });

        btnEliminarInvestigador.setText("Eliminar Investigador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminarInvestigador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarInvestigador)
                    .addComponent(btnAgregarPublicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarPublicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(btnAgregarInvestigador)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPublicacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarInvestigador)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPublicacion)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPublicacionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInvestigador;
    private javax.swing.JButton btnAgregarPublicacion;
    private javax.swing.JButton btnEliminarInvestigador;
    private javax.swing.JButton btnEliminarPublicacion;
    // End of variables declaration//GEN-END:variables
}
